services:
  pg:
    container_name: nano-management-pg
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nanomanagement
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - nano-management-pg:/var/lib/postgresql/data/pgdata

volumes:
  nano-management-pg:
    name: nano-management-pg
